// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RCP.Movie.Infrastructure;

#nullable disable

namespace RCP.Project.Migrations.Phim
{
    [DbContext(typeof(PhimDbContext))]
    partial class PhimDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RCP.Movie.Domain.Phim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("DangChieu")
                        .HasColumnType("bit");

                    b.Property<string>("DaoDien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DeleteBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DienVien")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKhoiChieu")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgonNgu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhanLoaiDoTuoi")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ThoiLuongPhut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Phim", "Movie");
                });

            modelBuilder.Entity("RCP.Movie.Domain.PhimAnh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("LaAnhChinh")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiAnh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PhimId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("PhimId");

                    b.ToTable("PhimAnh", "Movie");
                });

            modelBuilder.Entity("RCP.Movie.Domain.PhimTheLoai", b =>
                {
                    b.Property<int>("PhimId")
                        .HasColumnType("int");

                    b.Property<int>("TheLoaiId")
                        .HasColumnType("int");

                    b.HasKey("PhimId", "TheLoaiId");

                    b.HasIndex("TheLoaiId");

                    b.ToTable("PhimTheLoai", "Movie");
                });

            modelBuilder.Entity("RCP.Movie.Domain.PhimVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LoaiVideo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PhimId")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("PhimId");

                    b.ToTable("PhimVideo", "Movie");
                });

            modelBuilder.Entity("RCP.Movie.Domain.TheLoai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TheLoai", "Movie");
                });

            modelBuilder.Entity("RCP.Movie.Domain.PhimAnh", b =>
                {
                    b.HasOne("RCP.Movie.Domain.Phim", "Phim")
                        .WithMany("AnhList")
                        .HasForeignKey("PhimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phim");
                });

            modelBuilder.Entity("RCP.Movie.Domain.PhimTheLoai", b =>
                {
                    b.HasOne("RCP.Movie.Domain.Phim", "Phim")
                        .WithMany("PhimTheLoais")
                        .HasForeignKey("PhimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RCP.Movie.Domain.TheLoai", "TheLoai")
                        .WithMany("PhimTheLoais")
                        .HasForeignKey("TheLoaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phim");

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("RCP.Movie.Domain.PhimVideo", b =>
                {
                    b.HasOne("RCP.Movie.Domain.Phim", "Phim")
                        .WithMany("VideoList")
                        .HasForeignKey("PhimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phim");
                });

            modelBuilder.Entity("RCP.Movie.Domain.Phim", b =>
                {
                    b.Navigation("AnhList");

                    b.Navigation("PhimTheLoais");

                    b.Navigation("VideoList");
                });

            modelBuilder.Entity("RCP.Movie.Domain.TheLoai", b =>
                {
                    b.Navigation("PhimTheLoais");
                });
#pragma warning restore 612, 618
        }
    }
}
